export const COUNTRIES = [
    { "name": "Afghanistan", "code": "AF", "common": false },
    { "name": "Åland Islands", "code": "AX", "common": false },
    { "name": "Albania", "code": "AL", "common": false },
    { "name": "Algeria", "code": "DZ", "common": false },
    { "name": "American Samoa", "code": "AS", "common": false },
    { "name": "Andorra", "code": "AD", "common": false },
    { "name": "Angola", "code": "AO", "common": false },
    { "name": "Anguilla", "code": "AI", "common": false },
    { "name": "Antarctica", "code": "AQ", "common": false },
    { "name": "Antigua and Barbuda", "code": "AG", "common": false },
    { "name": "Argentina", "code": "AR", "common": false },
    { "name": "Armenia", "code": "AM", "common": false },
    { "name": "Aruba", "code": "AW", "common": false },
    { "name": "Australia", "code": "AU", "common": false },
    { "name": "Austria", "code": "AT", "common": false },
    { "name": "Azerbaijan", "code": "AZ", "common": false },
    { "name": "Bahamas", "code": "BS", "common": false },
    { "name": "Bahrain", "code": "BH", "common": false },
    { "name": "Bangladesh", "code": "BD", "common": false },
    { "name": "Barbados", "code": "BB", "common": false },
    { "name": "Belarus", "code": "BY", "common": false },
    { "name": "Belgium", "code": "BE", "common": false },
    { "name": "Belize", "code": "BZ", "common": false },
    { "name": "Benin", "code": "BJ", "common": false },
    { "name": "Bermuda", "code": "BM", "common": false },
    { "name": "Bhutan", "code": "BT", "common": false },
    { "name": "Bolivia", "code": "BO", "common": false },
    { "name": "Bosnia and Herzegovina", "code": "BA", "common": false },
    { "name": "Botswana", "code": "BW", "common": false },
    { "name": "Bouvet Island", "code": "BV", "common": false },
    { "name": "Brazil", "code": "BR", "common": false },
    { "name": "British Indian Ocean Territory", "code": "IO", "common": false },
    { "name": "Brunei Darussalam", "code": "BN", "common": false },
    { "name": "Bulgaria", "code": "BG", "common": false },
    { "name": "Burkina Faso", "code": "BF", "common": false },
    { "name": "Burundi", "code": "BI", "common": false },
    { "name": "Cambodia", "code": "KH", "common": false },
    { "name": "Cameroon", "code": "CM", "common": false },
    { "name": "Canada", "code": "CA", "common": false },
    { "name": "Cape Verde", "code": "CV", "common": false },
    { "name": "Cayman Islands", "code": "KY", "common": false },
    { "name": "Central African Republic", "code": "CF", "common": false },
    { "name": "Chad", "code": "TD", "common": false },
    { "name": "Chile", "code": "CL", "common": false },
    { "name": "China", "code": "CN", "common": true },
    { "name": "Christmas Island", "code": "CX", "common": false },
    { "name": "Cocos (Keeling) Islands", "code": "CC", "common": false },
    { "name": "Colombia", "code": "CO", "common": false },
    { "name": "Comoros", "code": "KM", "common": false },
    { "name": "Congo", "code": "CG", "common": false },
    { "name": "Congo, The Democratic Republic of the", "code": "CD", "common": false },
    { "name": "Cook Islands", "code": "CK", "common": false },
    { "name": "Costa Rica", "code": "CR", "common": false },
    { "name": "Cote D\"Ivoire", "code": "CI", "common": false },
    { "name": "Croatia", "code": "HR", "common": false },
    { "name": "Cuba", "code": "CU", "common": false },
    { "name": "Cyprus", "code": "CY", "common": false },
    { "name": "Czech Republic", "code": "CZ", "common": false },
    { "name": "Denmark", "code": "DK", "common": false },
    { "name": "Djibouti", "code": "DJ", "common": false },
    { "name": "Dominica", "code": "DM", "common": false },
    { "name": "Dominican Republic", "code": "DO", "common": false },
    { "name": "Ecuador", "code": "EC", "common": false },
    { "name": "Egypt", "code": "EG", "common": false },
    { "name": "El Salvador", "code": "SV", "common": false },
    { "name": "Equatorial Guinea", "code": "GQ", "common": false },
    { "name": "Eritrea", "code": "ER", "common": false },
    { "name": "Estonia", "code": "EE", "common": false },
    { "name": "Ethiopia", "code": "ET", "common": false },
    { "name": "Falkland Islands (Malvinas)", "code": "FK", "common": false },
    { "name": "Faroe Islands", "code": "FO", "common": false },
    { "name": "Fiji", "code": "FJ", "common": false },
    { "name": "Finland", "code": "FI", "common": false },
    { "name": "France", "code": "FR", "common": false },
    { "name": "French Guiana", "code": "GF", "common": false },
    { "name": "French Polynesia", "code": "PF", "common": false },
    { "name": "French Southern Territories", "code": "TF", "common": false },
    { "name": "Gabon", "code": "GA", "common": false },
    { "name": "Gambia", "code": "GM", "common": false },
    { "name": "Georgia", "code": "GE", "common": false },
    { "name": "Germany", "code": "DE", "common": true },
    { "name": "Ghana", "code": "GH", "common": false },
    { "name": "Gibraltar", "code": "GI", "common": false },
    { "name": "Greece", "code": "GR", "common": false },
    { "name": "Greenland", "code": "GL", "common": false },
    { "name": "Grenada", "code": "GD", "common": false },
    { "name": "Guadeloupe", "code": "GP", "common": false },
    { "name": "Guam", "code": "GU", "common": false },
    { "name": "Guatemala", "code": "GT", "common": false },
    { "name": "Guernsey", "code": "GG", "common": false },
    { "name": "Guinea", "code": "GN", "common": false },
    { "name": "Guinea-Bissau", "code": "GW", "common": false },
    { "name": "Guyana", "code": "GY", "common": false },
    { "name": "Haiti", "code": "HT", "common": false },
    { "name": "Heard Island and Mcdonald Islands", "code": "HM", "common": false },
    { "name": "Holy See (Vatican City State)", "code": "VA", "common": false },
    { "name": "Honduras", "code": "HN", "common": false },
    { "name": "Hong Kong", "code": "HK", "common": false },
    { "name": "Hungary", "code": "HU", "common": false },
    { "name": "Iceland", "code": "IS", "common": false },
    { "name": "India", "code": "IN", "common": false },
    { "name": "Indonesia", "code": "ID", "common": false },
    { "name": "Iran, Islamic Republic Of", "code": "IR", "common": false },
    { "name": "Iraq", "code": "IQ", "common": false },
    { "name": "Ireland", "code": "IE", "common": false },
    { "name": "Isle of Man", "code": "IM", "common": false },
    { "name": "Israel", "code": "IL", "common": false },
    { "name": "Italy", "code": "IT", "common": false },
    { "name": "Jamaica", "code": "JM", "common": false },
    { "name": "Japan", "code": "JP", "common": false },
    { "name": "Jersey", "code": "JE", "common": false },
    { "name": "Jordan", "code": "JO", "common": false },
    { "name": "Kazakhstan", "code": "KZ", "common": false },
    { "name": "Kenya", "code": "KE", "common": false },
    { "name": "Kiribati", "code": "KI", "common": false },
    { "name": "Korea, Democratic People\"S Republic of", "code": "KP", "common": false },
    { "name": "Korea, Republic of", "code": "KR", "common": false },
    { "name": "Kuwait", "code": "KW", "common": false },
    { "name": "Kyrgyzstan", "code": "KG", "common": false },
    { "name": "Lao People\"S Democratic Republic", "code": "LA", "common": false },
    { "name": "Latvia", "code": "LV", "common": false },
    { "name": "Lebanon", "code": "LB", "common": false },
    { "name": "Lesotho", "code": "LS", "common": false },
    { "name": "Liberia", "code": "LR", "common": false },
    { "name": "Libyan Arab Jamahiriya", "code": "LY", "common": false },
    { "name": "Liechtenstein", "code": "LI", "common": false },
    { "name": "Lithuania", "code": "LT", "common": false },
    { "name": "Luxembourg", "code": "LU", "common": false },
    { "name": "Macao", "code": "MO", "common": false },
    { "name": "Macedonia, The Former Yugoslav Republic of", "code": "MK", "common": false },
    { "name": "Madagascar", "code": "MG", "common": false },
    { "name": "Malawi", "code": "MW", "common": false },
    { "name": "Malaysia", "code": "MY", "common": false },
    { "name": "Maldives", "code": "MV", "common": false },
    { "name": "Mali", "code": "ML", "common": false },
    { "name": "Malta", "code": "MT", "common": false },
    { "name": "Marshall Islands", "code": "MH", "common": false },
    { "name": "Martinique", "code": "MQ", "common": false },
    { "name": "Mauritania", "code": "MR", "common": false },
    { "name": "Mauritius", "code": "MU", "common": false },
    { "name": "Mayotte", "code": "YT", "common": false },
    { "name": "Mexico", "code": "MX", "common": false },
    { "name": "Micronesia, Federated States of", "code": "FM", "common": false },
    { "name": "Moldova, Republic of", "code": "MD", "common": false },
    { "name": "Monaco", "code": "MC", "common": false },
    { "name": "Mongolia", "code": "MN", "common": false },
    { "name": "Montserrat", "code": "MS", "common": false },
    { "name": "Morocco", "code": "MA", "common": false },
    { "name": "Mozambique", "code": "MZ", "common": false },
    { "name": "Myanmar", "code": "MM", "common": false },
    { "name": "Namibia", "code": "NA", "common": false },
    { "name": "Nauru", "code": "NR", "common": false },
    { "name": "Nepal", "code": "NP", "common": false },
    { "name": "Netherlands", "code": "NL", "common": false },
    { "name": "Netherlands Antilles", "code": "AN", "common": false },
    { "name": "New Caledonia", "code": "NC", "common": false },
    { "name": "New Zealand", "code": "NZ", "common": false },
    { "name": "Nicaragua", "code": "NI", "common": false },
    { "name": "Niger", "code": "NE", "common": false },
    { "name": "Nigeria", "code": "NG", "common": false },
    { "name": "Niue", "code": "NU", "common": false },
    { "name": "Norfolk Island", "code": "NF", "common": false },
    { "name": "Northern Mariana Islands", "code": "MP", "common": false },
    { "name": "Norway", "code": "NO", "common": false },
    { "name": "Oman", "code": "OM", "common": false },
    { "name": "Pakistan", "code": "PK", "common": false },
    { "name": "Palau", "code": "PW", "common": false },
    { "name": "Palestinian Territory, Occupied", "code": "PS", "common": false },
    { "name": "Panama", "code": "PA", "common": false },
    { "name": "Papua New Guinea", "code": "PG", "common": false },
    { "name": "Paraguay", "code": "PY", "common": false },
    { "name": "Peru", "code": "PE", "common": false },
    { "name": "Philippines", "code": "PH", "common": false },
    { "name": "Pitcairn", "code": "PN", "common": false },
    { "name": "Poland", "code": "PL", "common": false },
    { "name": "Portugal", "code": "PT", "common": false },
    { "name": "Puerto Rico", "code": "PR", "common": false },
    { "name": "Qatar", "code": "QA", "common": false },
    { "name": "Reunion", "code": "RE", "common": false },
    { "name": "Romania", "code": "RO", "common": false },
    { "name": "Russian Federation", "code": "RU", "common": false },
    { "name": "RWANDA", "code": "RW", "common": false },
    { "name": "Saint Helena", "code": "SH", "common": false },
    { "name": "Saint Kitts and Nevis", "code": "KN", "common": false },
    { "name": "Saint Lucia", "code": "LC", "common": false },
    { "name": "Saint Pierre and Miquelon", "code": "PM", "common": false },
    { "name": "Saint Vincent and the Grenadines", "code": "VC", "common": false },
    { "name": "Samoa", "code": "WS", "common": false },
    { "name": "San Marino", "code": "SM", "common": false },
    { "name": "Sao Tome and Principe", "code": "ST", "common": false },
    { "name": "Saudi Arabia", "code": "SA", "common": false },
    { "name": "Senegal", "code": "SN", "common": false },
    { "name": "Serbia and Montenegro", "code": "CS", "common": false },
    { "name": "Seychelles", "code": "SC", "common": false },
    { "name": "Sierra Leone", "code": "SL", "common": false },
    { "name": "Singapore", "code": "SG", "common": false },
    { "name": "Slovakia", "code": "SK", "common": false },
    { "name": "Slovenia", "code": "SI", "common": false },
    { "name": "Solomon Islands", "code": "SB", "common": false },
    { "name": "Somalia", "code": "SO", "common": false },
    { "name": "South Africa", "code": "ZA", "common": false },
    { "name": "South Georgia and the South Sandwich Islands", "code": "GS", "common": false },
    { "name": "Spain", "code": "ES", "common": true },
    { "name": "Sri Lanka", "code": "LK", "common": false },
    { "name": "Sudan", "code": "SD", "common": false },
    { "name": "Suriname", "code": "SR", "common": false },
    { "name": "Svalbard and Jan Mayen", "code": "SJ", "common": false },
    { "name": "Swaziland", "code": "SZ", "common": false },
    { "name": "Sweden", "code": "SE", "common": false },
    { "name": "Switzerland", "code": "CH", "common": false },
    { "name": "Syrian Arab Republic", "code": "SY", "common": false },
    { "name": "Taiwan", "code": "TW", "common": false },
    { "name": "Tajikistan", "code": "TJ", "common": false },
    { "name": "Tanzania, United Republic of", "code": "TZ", "common": false },
    { "name": "Thailand", "code": "TH", "common": false },
    { "name": "Timor-Leste", "code": "TL", "common": false },
    { "name": "Togo", "code": "TG", "common": false },
    { "name": "Tokelau", "code": "TK", "common": false },
    { "name": "Tonga", "code": "TO", "common": false },
    { "name": "Trinidad and Tobago", "code": "TT", "common": false },
    { "name": "Tunisia", "code": "TN", "common": false },
    { "name": "Turkey", "code": "TR", "common": false },
    { "name": "Turkmenistan", "code": "TM", "common": false },
    { "name": "Turks and Caicos Islands", "code": "TC", "common": false },
    { "name": "Tuvalu", "code": "TV", "common": false },
    { "name": "Uganda", "code": "UG", "common": false },
    { "name": "Ukraine", "code": "UA", "common": false },
    { "name": "United Arab Emirates", "code": "AE", "common": false },
    { "name": "United Kingdom", "code": "GB", "common": true },
    { "name": "United States", "code": "US", "common": true },
    { "name": "United States Minor Outlying Islands", "code": "UM", "common": false },
    { "name": "Uruguay", "code": "UY", "common": false },
    { "name": "Uzbekistan", "code": "UZ", "common": false },
    { "name": "Vanuatu", "code": "VU", "common": false },
    { "name": "Venezuela", "code": "VE", "common": false },
    { "name": "Viet Nam", "code": "VN", "common": false },
    { "name": "Virgin Islands, British", "code": "VG", "common": false },
    { "name": "Virgin Islands, U.S.", "code": "VI", "common": false },
    { "name": "Wallis and Futuna", "code": "WF", "common": false },
    { "name": "Western Sahara", "code": "EH", "common": false },
    { "name": "Yemen", "code": "YE", "common": false },
    { "name": "Zambia", "code": "ZM", "common": false },
    { "name": "Zimbabwe", "code": "ZW", "common": false }
]