export const PHONE_COUNTRIES = [
  {
    name: "Azerbaijan",
    dialCode: "994",
    countryCode: "az",
    common: false,
  },
  {
    name: "Bosnia and Herzegovina",
    dialCode: "1242",
    countryCode: "bs",
    common: false,
  },
  {
    name: "",
    dialCode: "973",
    countryCode: "bh",
    common: false,
  },
  {
    name: "",
    dialCode: "880",
    countryCode: "bd",
    common: false,
  },
  {
    name: "",
    dialCode: "1246",
    countryCode: "bb",
    common: false,
  },
  {
    name: "",
    dialCode: "375",
    countryCode: "by",
    common: false,
  },
  {
    name: "",
    dialCode: "32",
    countryCode: "be",
    common: false,
  },
  {
    name: "",
    dialCode: "501",
    countryCode: "bz",
    common: false,
  },
  {
    name: "",
    dialCode: "229",
    countryCode: "bj",
    common: false,
  },
  {
    name: "",
    dialCode: "1441",
    countryCode: "bm",
    common: false,
  },
  {
    name: "",
    dialCode: "975",
    countryCode: "bt",
    common: false,
  },
  {
    name: "",
    dialCode: "591",
    countryCode: "bo",
    common: false,
  },
  {
    name: "",
    dialCode: "387",
    countryCode: "ba",
    common: false,
  },
  {
    name: "",
    dialCode: "267",
    countryCode: "bw",
    common: false,
  },
  {
    name: "",
    dialCode: "55",
    countryCode: "br",
    common: false,
  },
  {
    name: "",
    dialCode: "246",
    countryCode: "io",
    common: false,
  },
  {
    name: "",
    dialCode: "1284",
    countryCode: "vg",
    common: false,
  },
  {
    name: "",
    dialCode: "673",
    countryCode: "bn",
    common: false,
  },
  {
    name: "",
    dialCode: "359",
    countryCode: "bg",
    common: false,
  },
  {
    name: "",
    dialCode: "226",
    countryCode: "bf",
    common: false,
  },
  {
    name: "",
    dialCode: "257",
    countryCode: "bi",
    common: false,
  },
  {
    name: "",
    dialCode: "855",
    countryCode: "kh",
    common: false,
  },
  {
    name: "",
    dialCode: "237",
    countryCode: "cm",
    common: false,
  },
  {
    name: "",
    dialCode: "1",
    countryCode: "ca",
    common: false,
  },
  {
    name: "",
    dialCode: "238",
    countryCode: "cv",
    common: false,
  },
  {
    name: "",
    dialCode: "599",
    countryCode: "bq",
    common: false,
  },
  {
    name: "",
    dialCode: "1345",
    countryCode: "ky",
    common: false,
  },
  {
    name: "",
    dialCode: "236",
    countryCode: "cf",
    common: false,
  },
  {
    name: "",
    dialCode: "235",
    countryCode: "td",
    common: false,
  },
  {
    name: "",
    dialCode: "56",
    countryCode: "cl",
    common: false,
  },
  {
    name: "",
    dialCode: "86",
    countryCode: "cn",
    common: false,
  },
  {
    name: "",
    dialCode: "61",
    countryCode: "au",
    common: false,
  },
  {
    name: "",
    dialCode: "57",
    countryCode: "co",
    common: false,
  },
  {
    name: "",
    dialCode: "269",
    countryCode: "km",
    common: false,
  },
  {
    name: "",
    dialCode: "243",
    countryCode: "cd",
    common: false,
  },
  {
    name: "",
    dialCode: "242",
    countryCode: "cg",
    common: false,
  },
  {
    name: "",
    dialCode: "682",
    countryCode: "ck",
    common: false,
  },
  {
    name: "",
    dialCode: "506",
    countryCode: "cr",
    common: false,
  },
  {
    name: "",
    dialCode: "225",
    countryCode: "ci",
    common: false,
  },
  {
    name: "",
    dialCode: "385",
    countryCode: "hr",
    common: false,
  },
  {
    name: "",
    dialCode: "53",
    countryCode: "cu",
    common: false,
  },
  {
    name: "",
    dialCode: "599",
    countryCode: "cw",
    common: false,
  },
  {
    name: "",
    dialCode: "357",
    countryCode: "cy",
    common: false,
  },
  {
    name: "",
    dialCode: "420",
    countryCode: "cz",
    common: false,
  },
  {
    name: "",
    dialCode: "45",
    countryCode: "dk",
    common: false,
  },
  {
    name: "",
    dialCode: "253",
    countryCode: "dj",
    common: false,
  },
  {
    name: "",
    dialCode: "1767",
    countryCode: "dm",
    common: false,
  },
  {
    name: "",
    dialCode: "1",
    countryCode: "do",
    common: false,
  },
  {
    name: "",
    dialCode: "593",
    countryCode: "ec",
    common: false,
  },
  {
    name: "",
    dialCode: "20",
    countryCode: "eg",
  },
  {
    name: "",
    dialCode: "503",
    countryCode: "sv",
    common: false,
  },
  {
    name: "",
    dialCode: "240",
    countryCode: "gq",
    common: false,
  },
  {
    name: "",
    dialCode: "291",
    countryCode: "er",
    common: false,
  },
  {
    name: "",
    dialCode: "372",
    countryCode: "ee",
    common: false,
  },
  {
    name: "",
    dialCode: "251",
    countryCode: "et",
    common: false,
  },
  {
    name: "",
    dialCode: "500",
    countryCode: "fk",
    common: false,
  },
  {
    name: "",
    dialCode: "298",
    countryCode: "fo",
    common: false,
  },
  {
    name: "",
    dialCode: "679",
    countryCode: "fj",
    common: false,
  },
  {
    name: "",
    dialCode: "358",
    countryCode: "fi",
    common: false,
  },
  {
    name: "",
    dialCode: "33",
    countryCode: "fr",
    common: false,
  },
  {
    name: "",
    dialCode: "594",
    countryCode: "gf",
    common: false,
  },
  {
    name: "",
    dialCode: "689",
    countryCode: "pf",
    common: false,
  },
  {
    name: "",
    dialCode: "241",
    countryCode: "ga",
  },
  {
    name: "",
    dialCode: "220",
    countryCode: "gm",
    common: false,
  },
  {
    name: "",
    dialCode: "995",
    countryCode: "ge",
    common: false,
  },
  {
    name: "",
    dialCode: "49",
    countryCode: "de",
    common: false,
  },
  {
    name: "",
    dialCode: "233",
    countryCode: "gh",
    common: false,
  },
  {
    name: "",
    dialCode: "350",
    countryCode: "gi",
    common: false,
  },
  {
    name: "",
    dialCode: "30",
    countryCode: "gr",
    common: false,
  },
  {
    name: "",
    dialCode: "299",
    countryCode: "gl",
    common: false,
  },
  {
    name: "",
    dialCode: "1473",
    countryCode: "gd",
    common: false,
  },
  {
    name: "",
    dialCode: "590",
    countryCode: "gp",
    common: false,
  },
  {
    name: "",
    dialCode: "1671",
    countryCode: "gu",
    common: false,
  },
  {
    name: "",
    dialCode: "502",
    countryCode: "gt",
    common: false,
  },
  {
    name: "",
    dialCode: "44",
    countryCode: "gg",
    common: false,
  },
  {
    name: "",
    dialCode: "224",
    countryCode: "gn",
    common: false,
  },
  {
    name: "",
    dialCode: "245",
    countryCode: "gw",
    common: false,
  },
  {
    name: "",
    dialCode: "592",
    countryCode: "gy",
    common: false,
  },
  {
    name: "",
    dialCode: "509",
    countryCode: "ht",
    common: false,
  },
  {
    name: "",
    dialCode: "504",
    countryCode: "hn",
    common: false,
  },
  {
    name: "",
    dialCode: "852",
    countryCode: "hk",
    common: false,
  },
  {
    name: "",
    dialCode: "36",
    countryCode: "hu",
    common: false,
  },
  {
    name: "",
    dialCode: "354",
    countryCode: "is",
    common: false,
  },
  {
    name: "",
    dialCode: "91",
    countryCode: "in",
    common: false,
  },
  {
    name: "",
    dialCode: "62",
    countryCode: "id",
    common: false,
  },
  {
    name: "",
    dialCode: "98",
    countryCode: "ir",
    common: false,
  },
  {
    name: "",
    dialCode: "964",
    countryCode: "iq",
    common: false,
  },
  {
    name: "",
    dialCode: "353",
    countryCode: "ie",
    common: false,
  },
  {
    name: "",
    dialCode: "44",
    countryCode: "im",
  },
  {
    name: "",
    dialCode: "972",
    countryCode: "il",
    common: false,
  },
  {
    name: "",
    dialCode: "39",
    countryCode: "it",
    common: true,
  },
  {
    name: "",
    dialCode: "1876",
    countryCode: "jm",
    common: false,
  },
  {
    name: "",
    dialCode: "81",
    countryCode: "jp",
  },
  {
    name: "",
    dialCode: "44",
    countryCode: "je",
    common: false,
  },
  {
    name: "",
    dialCode: "962",
    countryCode: "jo",
    common: false,
  },
  {
    name: "",
    dialCode: "7",
    countryCode: "kz",
    common: false,
  },
  {
    name: "",
    dialCode: "254",
    countryCode: "ke",
  },
  {
    name: "",
    dialCode: "686",
    countryCode: "ki",
    common: false,
  },
  {
    name: "",
    dialCode: "383",
    countryCode: "xk",
  },
  {
    name: "",
    dialCode: "965",
    countryCode: "kw",
    common: false,
  },
  {
    name: "",
    dialCode: "996",
    countryCode: "kg",
  },
  {
    name: "",
    dialCode: "856",
    countryCode: "la",
    common: false,
  },
  {
    name: "",
    dialCode: "371",
    countryCode: "lv",
    common: false,
  },
  {
    name: "",
    dialCode: "961",
    countryCode: "lb",
    common: false,
  },
  {
    name: "",
    dialCode: "266",
    countryCode: "ls",
    common: false,
  },
  {
    name: "",
    dialCode: "231",
    countryCode: "lr",
    common: false,
  },
  {
    name: "",
    dialCode: "218",
    countryCode: "ly",
    common: false,
  },
  {
    name: "",
    dialCode: "423",
    countryCode: "li",
    common: false,
  },
  {
    name: "",
    dialCode: "370",
    countryCode: "lt",
    common: false,
  },
  {
    name: "",
    dialCode: "352",
    countryCode: "lu",
    common: false,
  },
  {
    name: "",
    dialCode: "853",
    countryCode: "mo",
    common: false,
  },
  {
    name: "",
    dialCode: "389",
    countryCode: "mk",
    common: false,
  },
  {
    name: "",
    dialCode: "261",
    countryCode: "mg",
    common: false,
  },
  {
    name: "",
    dialCode: "265",
    countryCode: "mw",
    common: false,
  },
  {
    name: "",
    dialCode: "60",
    countryCode: "my",
  },
  {
    name: "",
    dialCode: "960",
    countryCode: "mv",
    common: false,
  },
  {
    name: "",
    dialCode: "223",
    countryCode: "ml",
    common: false,
  },
  {
    name: "",
    dialCode: "356",
    countryCode: "mt",
    common: false,
  },
  {
    name: "",
    dialCode: "692",
    countryCode: "mh",
    common: false,
  },
  {
    name: "",
    dialCode: "596",
    countryCode: "mq",
    common: false,
  },
  {
    name: "",
    dialCode: "222",
    countryCode: "mr",
    common: false,
  },
  {
    name: "",
    dialCode: "230",
    countryCode: "mu",
    common: false,
  },
  {
    name: "",
    dialCode: "262",
    countryCode: "yt",
    common: false,
  },
  {
    name: "",
    dialCode: "52",
    countryCode: "mx",
    common: false,
  },
  {
    name: "",
    dialCode: "691",
    countryCode: "fm",
    common: false,
  },
  {
    name: "",
    dialCode: "373",
    countryCode: "md",
    common: false,
  },
  {
    name: "",
    dialCode: "377",
    countryCode: "mc",
    common: false,
  },
  {
    name: "",
    dialCode: "976",
    countryCode: "mn",
    common: false,
  },
  {
    name: "",
    dialCode: "382",
    countryCode: "me",
    common: false,
  },
  {
    name: "",
    dialCode: "1664",
    countryCode: "ms",
    common: false,
  },
  {
    name: "",
    dialCode: "212",
    countryCode: "ma",
    common: false,
  },
  {
    name: "",
    dialCode: "258",
    countryCode: "mz",
    common: false,
  },
  {
    name: "",
    dialCode: "95",
    countryCode: "mm",
    common: false,
  },
  {
    name: "",
    dialCode: "264",
    countryCode: "na",
    common: false,
  },
  {
    name: "",
    dialCode: "674",
    countryCode: "nr",
    common: false,
  },
  {
    name: "",
    dialCode: "977",
    countryCode: "np",
    common: false,
  },
  {
    name: "",
    dialCode: "31",
    countryCode: "nl",
    common: false,
  },
  {
    name: "",
    dialCode: "687",
    countryCode: "nc",
    common: false,
  },
  {
    name: "",
    dialCode: "64",
    countryCode: "nz",
    common: false,
  },
  {
    name: "",
    dialCode: "505",
    countryCode: "ni",
    common: false,
  },
  {
    name: "",
    dialCode: "227",
    countryCode: "ne",
    common: false,
  },
  {
    name: "",
    dialCode: "234",
    countryCode: "ng",
    common: false,
  },
  {
    name: "",
    dialCode: "683",
    countryCode: "nu",
    common: false,
  },
  {
    name: "",
    dialCode: "672",
    countryCode: "nf",
    common: false,
  },
  {
    name: "",
    dialCode: "850",
    countryCode: "kp",
    common: false,
  },
  {
    name: "",
    dialCode: "1670",
    countryCode: "mp",
    common: false,
  },
  {
    name: "",
    dialCode: "47",
    countryCode: "no",
    common: false,
  },
  {
    name: "",
    dialCode: "968",
    countryCode: "om",
    common: false,
  },
  {
    name: "",
    dialCode: "92",
    countryCode: "pk",
    common: false,
  },
  {
    name: "",
    dialCode: "680",
    countryCode: "pw",
    common: false,
  },
  {
    name: "",
    dialCode: "970",
    countryCode: "ps",
    common: false,
  },
  {
    name: "",
    dialCode: "507",
    countryCode: "pa",
    common: false,
  },
  {
    name: "",
    dialCode: "675",
    countryCode: "pg",
  },
  {
    name: "",
    dialCode: "595",
    countryCode: "py",
    common: false,
  },
  {
    name: "",
    dialCode: "51",
    countryCode: "pe",
  },
  {
    name: "",
    dialCode: "63",
    countryCode: "ph",
    common: false,
  },
  {
    name: "",
    dialCode: "48",
    countryCode: "pl",
    common: false,
  },
  {
    name: "",
    dialCode: "351",
    countryCode: "pt",
    common: false,
  },
  {
    name: "",
    dialCode: "1",
    countryCode: "pr",
    common: false,
  },
  {
    name: "",
    dialCode: "974",
    countryCode: "qa",
    common: false,
  },
  {
    name: "",
    dialCode: "262",
    countryCode: "re",
    common: false,
  },
  {
    name: "",
    dialCode: "40",
    countryCode: "ro",
    common: false,
  },
  {
    name: "",
    dialCode: "7",
    countryCode: "ru",
    common: false,
  },
  {
    name: "",
    dialCode: "250",
    countryCode: "rw",
    common: false,
  },
  {
    name: "",
    dialCode: "590",
    countryCode: "bl",
    common: false,
  },
  {
    name: "",
    dialCode: "290",
    countryCode: "sh",
    common: false,
  },
  {
    name: "",
    dialCode: "1869",
    countryCode: "kn",
  },
  {
    name: "",
    dialCode: "1758",
    countryCode: "lc",
  },
  {
    name: "",
    dialCode: "508",
    countryCode: "pm",
    common: false,
  },
  {
    name: "",
    dialCode: "1784",
    countryCode: "vc",
    common: false,
  },
  {
    name: "",
    dialCode: "685",
    countryCode: "ws",
    common: false,
  },
  {
    name: "",
    dialCode: "378",
    countryCode: "sm",
    common: false,
  },
  {
    name: "",
    dialCode: "239",
    countryCode: "st",
  },
  {
    name: "",
    dialCode: "966",
    countryCode: "sa",
  },
  {
    name: "",
    dialCode: "221",
    countryCode: "sn",
  },
  {
    name: "",
    dialCode: "381",
    countryCode: "rs",
    common: false,
  },
  {
    name: "",
    dialCode: "248",
    countryCode: "sc",
    common: false,
  },
  {
    name: "",
    dialCode: "232",
    countryCode: "sl",
    common: false,
  },
  {
    name: "",
    dialCode: "65",
    countryCode: "sg",
    common: false,
  },
  {
    name: "",
    dialCode: "1721",
    countryCode: "sx",
    common: false,
  },
  {
    name: "",
    dialCode: "421",
    countryCode: "sk",
    common: false,
  },
  {
    name: "",
    dialCode: "386",
    countryCode: "si",
    common: false,
  },
  {
    name: "",
    dialCode: "677",
    countryCode: "sb",
    common: false,
  },
  {
    name: "",
    dialCode: "252",
    countryCode: "so",
    common: false,
  },
  {
    name: "",
    dialCode: "27",
    countryCode: "za",
    common: false,
  },
  {
    name: "",
    dialCode: "82",
    common: false,
    countryCode: "kr",
  },
  {
    name: "",
    dialCode: "211",
    common: false,
    countryCode: "ss",
  },
  {
    name: "",
    dialCode: "34",
    common: true,
    countryCode: "es",
  },
  {
    name: "",
    dialCode: "94",
    common: false,
    countryCode: "lk",
  },
  {
    name: "",
    dialCode: "249",
    common: false,
    countryCode: "sd",
  },
  {
    name: "",
    dialCode: "597",
    common: false,
    countryCode: "sr",
  },
  {
    name: "",
    dialCode: "47",
    common: false,
    countryCode: "sj",
  },
  {
    name: "",
    dialCode: "268",
    countryCode: "sz",
  },
  {
    name: "",
    dialCode: "46",
    countryCode: "se",
  },
  {
    name: "",
    dialCode: "41",
    countryCode: "ch",
  },
  {
    name: "",
    dialCode: "963",
    countryCode: "sy",
  },
  {
    name: "",
    dialCode: "886",
    countryCode: "tw",
  },
  {
    name: "",
    dialCode: "992",
    countryCode: "tj",
  },
  {
    name: "",
    dialCode: "255",
    countryCode: "tz",
  },
  {
    name: "",
    dialCode: "66",
    countryCode: "th",
  },
  {
    name: "",
    dialCode: "670",
    countryCode: "tl",
  },
  {
    name: "",
    dialCode: "228",
    countryCode: "tg",
  },
  {
    name: "",
    dialCode: "690",
    countryCode: "tk",
  },
  {
    name: "",
    dialCode: "676",
    countryCode: "to",
  },
  {
    name: "",
    dialCode: "1868",
    countryCode: "tt",
  },
  {
    name: "",
    dialCode: "216",
    countryCode: "tn",
  },
  {
    name: "",
    dialCode: "90",
    countryCode: "tr",
  },
  {
    name: "",
    dialCode: "993",
    countryCode: "tm",
  },
  {
    name: "",
    dialCode: "1649",
    countryCode: "tc",
  },
  {
    name: "",
    dialCode: "688",
    countryCode: "tv",
  },
  {
    name: "",
    dialCode: "1340",
    countryCode: "vi",
  },
  {
    name: "",
    dialCode: "256",
    countryCode: "ug",
  },
  {
    name: "",
    dialCode: "380",
    countryCode: "ua",
  },
  {
    name: "",
    dialCode: "971",
    countryCode: "ae",
  },
  {
    name: "",
    dialCode: "44",
    countryCode: "gb",
    common: true,
  },
  {
    name: "",
    dialCode: "1",
    countryCode: "us",
    common: true,
  },
  {
    name: "",
    dialCode: "598",
    countryCode: "uy",
  },
  {
    name: "",
    dialCode: "998",
    countryCode: "uz",
  },
  {
    name: "",
    dialCode: "678",
    countryCode: "vu",
  },
  {
    name: "",
    dialCode: "39",
    countryCode: "va",
  },
  {
    name: "",
    dialCode: "58",
    countryCode: "ve",
  },
  {
    name: "",
    dialCode: "84",
    countryCode: "vn",
  },
  {
    name: "",
    dialCode: "681",
    countryCode: "wf",
  },
  {
    name: "",
    dialCode: "212",
    countryCode: "eh",
  },
  {
    name: "",
    dialCode: "967",
    countryCode: "ye",
  },
  {
    name: "",
    dialCode: "260",
    countryCode: "zm",
  },
  {
    name: "",
    dialCode: "263",
    countryCode: "zw",
  },
  {
    name: "",
    dialCode: "358",
    countryCode: "ax",
  },
];
