export interface TaxCode {
  id: string;
  country: string;
  tax_code: string;
  label: string;
  country_name: string;
}

export const TAX_CODES: TaxCode[] = [
  {
    id: "ad_nrt",
    country: "ad",
    tax_code: "nrt",
    label: "AD NRT",
    country_name: "Andorra",
  },
  {
    id: "ae_trn",
    country: "ae",
    tax_code: "trn",
    label: "AE TRN",
    country_name: "United Arab Emirates",
  },
  {
    id: "al_tin",
    country: "al",
    tax_code: "tin",
    label: "AL TIN",
    country_name: "Albania",
  },
  {
    id: "am_tin",
    country: "am",
    tax_code: "tin",
    label: "AM TIN",
    country_name: "Armenia",
  },
  {
    id: "ao_tin",
    country: "ao",
    tax_code: "tin",
    label: "AO TIN",
    country_name: "Angola",
  },
  {
    id: "ar_cuit",
    country: "ar",
    tax_code: "cuit",
    label: "AR CUIT",
    country_name: "Argentina",
  },
  {
    id: "au_abn",
    country: "au",
    tax_code: "abn",
    label: "AU ABN",
    country_name: "Australia",
  },
  {
    id: "au_arn",
    country: "au",
    tax_code: "arn",
    label: "AU ARN",
    country_name: "Australia",
  },
  {
    id: "aw_tin",
    country: "aw",
    tax_code: "tin",
    label: "AW TIN",
    country_name: "Aruba",
  },
  {
    id: "az_tin",
    country: "az",
    tax_code: "tin",
    label: "AZ TIN",
    country_name: "Azerbaijan",
  },
  {
    id: "ba_tin",
    country: "ba",
    tax_code: "tin",
    label: "BA TIN",
    country_name: "Bosnia and Herzegovina",
  },
  {
    id: "bb_tin",
    country: "bb",
    tax_code: "tin",
    label: "BB TIN",
    country_name: "Barbados",
  },
  {
    id: "bd_bin",
    country: "bd",
    tax_code: "bin",
    label: "BD BIN",
    country_name: "Bangladesh",
  },
  {
    id: "bf_ifu",
    country: "bf",
    tax_code: "ifu",
    label: "BF IFU",
    country_name: "Burkina Faso",
  },
  {
    id: "bg_uic",
    country: "bg",
    tax_code: "uic",
    label: "BG UIC",
    country_name: "Bulgaria",
  },
  {
    id: "bh_vat",
    country: "bh",
    tax_code: "vat",
    label: "BH VAT",
    country_name: "Bahrain",
  },
  {
    id: "bj_ifu",
    country: "bj",
    tax_code: "ifu",
    label: "BJ IFU",
    country_name: "Benin",
  },
  {
    id: "bo_tin",
    country: "bo",
    tax_code: "tin",
    label: "BO TIN",
    country_name: "Bolivia",
  },
  {
    id: "br_cnpj",
    country: "br",
    tax_code: "cnpj",
    label: "BR CNPJ",
    country_name: "Brazil",
  },
  {
    id: "br_cpf",
    country: "br",
    tax_code: "cpf",
    label: "BR CPF",
    country_name: "Brazil",
  },
  {
    id: "bs_tin",
    country: "bs",
    tax_code: "tin",
    label: "BS TIN",
    country_name: "Bahamas",
  },
  {
    id: "by_tin",
    country: "by",
    tax_code: "tin",
    label: "BY TIN",
    country_name: "Belarus",
  },
  {
    id: "ca_bn",
    country: "ca",
    tax_code: "bn",
    label: "CA BN",
    country_name: "Canada",
  },
  {
    id: "ca_gst_hst",
    country: "ca",
    tax_code: "gst_hst",
    label: "CA GST HST",
    country_name: "Canada",
  },
  {
    id: "ca_pst_bc",
    country: "ca",
    tax_code: "pst_bc",
    label: "CA PST BC",
    country_name: "Canada",
  },
  {
    id: "ca_pst_mb",
    country: "ca",
    tax_code: "pst_mb",
    label: "CA PST MB",
    country_name: "Canada",
  },
  {
    id: "ca_pst_sk",
    country: "ca",
    tax_code: "pst_sk",
    label: "CA PST SK",
    country_name: "Canada",
  },
  {
    id: "ca_qst",
    country: "ca",
    tax_code: "qst",
    label: "CA QST",
    country_name: "Canada",
  },
  {
    id: "cd_nif",
    country: "cd",
    tax_code: "nif",
    label: "CD NIF",
    country_name: "Congo",
  },
  {
    id: "ch_uid",
    country: "ch",
    tax_code: "uid",
    label: "CH UID",
    country_name: "Switzerland",
  },
  {
    id: "ch_vat",
    country: "ch",
    tax_code: "vat",
    label: "CH VAT",
    country_name: "Switzerland",
  },
  {
    id: "cl_tin",
    country: "cl",
    tax_code: "tin",
    label: "CL TIN",
    country_name: "Chile",
  },
  {
    id: "cm_niu",
    country: "cm",
    tax_code: "niu",
    label: "CM NIU",
    country_name: "Cameroon",
  },
  {
    id: "cn_tin",
    country: "cn",
    tax_code: "tin",
    label: "CN TIN",
    country_name: "China",
  },
  {
    id: "co_nit",
    country: "co",
    tax_code: "nit",
    label: "CO NIT",
    country_name: "Colombia",
  },
  {
    id: "cr_tin",
    country: "cr",
    tax_code: "tin",
    label: "CR TIN",
    country_name: "Costa Rica",
  },
  {
    id: "cv_nif",
    country: "cv",
    tax_code: "nif",
    label: "CV NIF",
    country_name: "Cape Verde",
  },
  {
    id: "de_stn",
    country: "de",
    tax_code: "stn",
    label: "DE STN",
    country_name: "Germany",
  },
  {
    id: "do_rcn",
    country: "do",
    tax_code: "rcn",
    label: "DO RCN",
    country_name: "Dominican Republic",
  },
  {
    id: "ec_ruc",
    country: "ec",
    tax_code: "ruc",
    label: "EC RUC",
    country_name: "Ecuador",
  },
  {
    id: "eg_tin",
    country: "eg",
    tax_code: "tin",
    label: "EG TIN",
    country_name: "Egypt",
  },
  {
    id: "es_cif",
    country: "es",
    tax_code: "cif",
    label: "ES CIF",
    country_name: "Spain",
  },
  {
    id: "et_tin",
    country: "et",
    tax_code: "tin",
    label: "ET TIN",
    country_name: "Ethiopia",
  },
  {
    id: "eu_oss_vat",
    country: "eu",
    tax_code: "oss_vat",
    label: "EU OSS VAT",
    country_name: "European Union",
  },
  {
    id: "eu_vat",
    country: "eu",
    tax_code: "vat",
    label: "EU VAT",
    country_name: "European Union",
  },
  {
    id: "gb_vat",
    country: "gb",
    tax_code: "vat",
    label: "GB VAT",
    country_name: "United Kingdom",
  },
  {
    id: "ge_vat",
    country: "ge",
    tax_code: "vat",
    label: "GE VAT",
    country_name: "Georgia",
  },
  {
    id: "gn_nif",
    country: "gn",
    tax_code: "nif",
    label: "GN NIF",
    country_name: "Guinea",
  },
  {
    id: "hk_br",
    country: "hk",
    tax_code: "br",
    label: "HK BR",
    country_name: "Hong Kong",
  },
  {
    id: "hr_oib",
    country: "hr",
    tax_code: "oib",
    label: "HR OIB",
    country_name: "Croatia",
  },
  {
    id: "hu_tin",
    country: "hu",
    tax_code: "tin",
    label: "HU TIN",
    country_name: "Hungary",
  },
  {
    id: "id_npwp",
    country: "id",
    tax_code: "npwp",
    label: "ID NPWP",
    country_name: "Indonesia",
  },
  {
    id: "il_vat",
    country: "il",
    tax_code: "vat",
    label: "IL VAT",
    country_name: "Israel",
  },
  {
    id: "in_gst",
    country: "in",
    tax_code: "gst",
    label: "IN GST",
    country_name: "India",
  },
  {
    id: "is_vat",
    country: "is",
    tax_code: "vat",
    label: "IS VAT",
    country_name: "Iceland",
  },
  {
    id: "jp_cn",
    country: "jp",
    tax_code: "cn",
    label: "JP CN",
    country_name: "Japan",
  },
  {
    id: "jp_rn",
    country: "jp",
    tax_code: "rn",
    label: "JP RN",
    country_name: "Japan",
  },
  {
    id: "jp_trn",
    country: "jp",
    tax_code: "trn",
    label: "JP TRN",
    country_name: "Japan",
  },
  {
    id: "ke_pin",
    country: "ke",
    tax_code: "pin",
    label: "KE PIN",
    country_name: "Kenya",
  },
  {
    id: "kg_tin",
    country: "kg",
    tax_code: "tin",
    label: "KG TIN",
    country_name: "Kyrgyzstan",
  },
  {
    id: "kh_tin",
    country: "kh",
    tax_code: "tin",
    label: "KH TIN",
    country_name: "Cambodia",
  },
  {
    id: "kr_brn",
    country: "kr",
    tax_code: "brn",
    label: "KR BRN",
    country_name: "South Korea",
  },
  {
    id: "kz_bin",
    country: "kz",
    tax_code: "bin",
    label: "KZ BIN",
    country_name: "Kazakhstan",
  },
  {
    id: "la_tin",
    country: "la",
    tax_code: "tin",
    label: "LA TIN",
    country_name: "Laos",
  },
  {
    id: "li_uid",
    country: "li",
    tax_code: "uid",
    label: "LI UID",
    country_name: "Liechtenstein",
  },
  {
    id: "li_vat",
    country: "li",
    tax_code: "vat",
    label: "LI VAT",
    country_name: "Liechtenstein",
  },
  {
    id: "ma_vat",
    country: "ma",
    tax_code: "vat",
    label: "MA VAT",
    country_name: "Morocco",
  },
  {
    id: "md_vat",
    country: "md",
    tax_code: "vat",
    label: "MD VAT",
    country_name: "Moldova",
  },
  {
    id: "me_pib",
    country: "me",
    tax_code: "pib",
    label: "ME PIB",
    country_name: "Montenegro",
  },
  {
    id: "mk_vat",
    country: "mk",
    tax_code: "vat",
    label: "MK VAT",
    country_name: "North Macedonia",
  },
  {
    id: "mr_nif",
    country: "mr",
    tax_code: "nif",
    label: "MR NIF",
    country_name: "Mauritania",
  },
  {
    id: "mx_rfc",
    country: "mx",
    tax_code: "rfc",
    label: "MX RFC",
    country_name: "Mexico",
  },
  {
    id: "my_frp",
    country: "my",
    tax_code: "frp",
    label: "MY FRP",
    country_name: "Malaysia",
  },
  {
    id: "my_itn",
    country: "my",
    tax_code: "itn",
    label: "MY ITN",
    country_name: "Malaysia",
  },
  {
    id: "my_sst",
    country: "my",
    tax_code: "sst",
    label: "MY SST",
    country_name: "Malaysia",
  },
  {
    id: "ng_tin",
    country: "ng",
    tax_code: "tin",
    label: "NG TIN",
    country_name: "Nigeria",
  },
  {
    id: "no_vat",
    country: "no",
    tax_code: "vat",
    label: "NO VAT",
    country_name: "Norway",
  },
  {
    id: "no_voec",
    country: "no",
    tax_code: "voec",
    label: "NO VOEC",
    country_name: "Norway",
  },
  {
    id: "np_pan",
    country: "np",
    tax_code: "pan",
    label: "NP PAN",
    country_name: "Nepal",
  },
  {
    id: "nz_gst",
    country: "nz",
    tax_code: "gst",
    label: "NZ GST",
    country_name: "New Zealand",
  },
  {
    id: "om_vat",
    country: "om",
    tax_code: "vat",
    label: "OM VAT",
    country_name: "Oman",
  },
  {
    id: "pe_ruc",
    country: "pe",
    tax_code: "ruc",
    label: "PE RUC",
    country_name: "Peru",
  },
  {
    id: "ph_tin",
    country: "ph",
    tax_code: "tin",
    label: "PH TIN",
    country_name: "Philippines",
  },
  {
    id: "ro_tin",
    country: "ro",
    tax_code: "tin",
    label: "RO TIN",
    country_name: "Romania",
  },
  {
    id: "rs_pib",
    country: "rs",
    tax_code: "pib",
    label: "RS PIB",
    country_name: "Serbia",
  },
  {
    id: "ru_inn",
    country: "ru",
    tax_code: "inn",
    label: "RU INN",
    country_name: "Russia",
  },
  {
    id: "ru_kpp",
    country: "ru",
    tax_code: "kpp",
    label: "RU KPP",
    country_name: "Russia",
  },
  {
    id: "sa_vat",
    country: "sa",
    tax_code: "vat",
    label: "SA VAT",
    country_name: "Saudi Arabia",
  },
  {
    id: "sg_gst",
    country: "sg",
    tax_code: "gst",
    label: "SG GST",
    country_name: "Singapore",
  },
  {
    id: "sg_uen",
    country: "sg",
    tax_code: "uen",
    label: "SG UEN",
    country_name: "Singapore",
  },
  {
    id: "si_tin",
    country: "si",
    tax_code: "tin",
    label: "SI TIN",
    country_name: "Slovenia",
  },
  {
    id: "sn_ninea",
    country: "sn",
    tax_code: "ninea",
    label: "SN NINEA",
    country_name: "Senegal",
  },
  {
    id: "sr_fin",
    country: "sr",
    tax_code: "fin",
    label: "SR FIN",
    country_name: "Suriname",
  },
  {
    id: "sv_nit",
    country: "sv",
    tax_code: "nit",
    label: "SV NIT",
    country_name: "El Salvador",
  },
  {
    id: "th_vat",
    country: "th",
    tax_code: "vat",
    label: "TH VAT",
    country_name: "Thailand",
  },
  {
    id: "tj_tin",
    country: "tj",
    tax_code: "tin",
    label: "TJ TIN",
    country_name: "Tajikistan",
  },
  {
    id: "tr_tin",
    country: "tr",
    tax_code: "tin",
    label: "TR TIN",
    country_name: "Turkey",
  },
  {
    id: "ug_tin",
    country: "ug",
    tax_code: "tin",
    label: "UG TIN",
    country_name: "Uganda",
  },
  {
    id: "unknown",
    country: "unknown",
    tax_code: "unknown",
    label: "UNKNOWN",
    country_name: "Unknown",
  },
  {
    id: "us_ein",
    country: "us",
    tax_code: "ein",
    label: "US EIN",
    country_name: "United States",
  },
  {
    id: "uy_ruc",
    country: "uy",
    tax_code: "ruc",
    label: "UY RUC",
    country_name: "Uruguay",
  },
  {
    id: "uz_tin",
    country: "uz",
    tax_code: "tin",
    label: "UZ TIN",
    country_name: "Uzbekistan",
  },
  {
    id: "uz_vat",
    country: "uz",
    tax_code: "vat",
    label: "UZ VAT",
    country_name: "Uzbekistan",
  },
  {
    id: "ve_rif",
    country: "ve",
    tax_code: "rif",
    label: "VE RIF",
    country_name: "Venezuela",
  },
  {
    id: "vn_tin",
    country: "vn",
    tax_code: "tin",
    label: "VN TIN",
    country_name: "Vietnam",
  },
  {
    id: "za_vat",
    country: "za",
    tax_code: "vat",
    label: "ZA VAT",
    country_name: "South Africa",
  },
  {
    id: "zm_tin",
    country: "zm",
    tax_code: "tin",
    label: "ZM TIN",
    country_name: "Zambia",
  },
  {
    id: "zw_tin",
    country: "zw",
    tax_code: "tin",
    label: "ZW TIN",
    country_name: "Zimbabwe",
  },
];

export default TAX_CODES;
